FROM python:2.7
 
COPY . /usr/src/app

WORKDIR /usr/src/app
ENV HOME /usr/src/app

# Install app requirements
RUN pip install -r requirements.txt

#CMD ["/bin/bash"]

ENTRYPOINT ["python"]
CMD ["app.py"]

